version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          GOPATH: /home/circleci/github.com/ap-communications/cq
          GO15VENDOREXPERIMENT: 1
    working_directory: /home/circleci/github.com/ap-communications/cq
    steps:
      - checkout
      - run:
          name: Install glide command
          command: sudo apt -y install golang-glide
      - run:
          name: Install dependencies library
          command: cd src/ && glide install
      - run:
          name: Build
          command: go build src/cq.go
      - run:
          name: Show version
          command: ./cq version
