version: 2

jobs:

  test:
    working_directory: /go/src/github.com/ap-communications/cq
    docker:
      - image: circleci/golang:1.12.5
        environment:
          GOPATH: /go
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          key: gomodules-{{ checksum "go.sum" }}
      - run:
          name: Install dependency libraries
          command: go mod download
      - run:
          name: Run test
          command: make test
      - save_cache:
          key: gomodules-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/

  build:
    working_directory: /go/src/github.com/ap-communications/cq
    docker:
      - image: circleci/golang:1.12.5
        environment:
          GOPATH: /go
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          key: gomodules-{{ checksum "go.sum" }}
      - run:
          name: Install dependency libraries
          command: go mod download
      - run:
          name: Cross compile
          command: make cross-compile
      - run:
          name: Create artifacts directory
          command: mkdir -p /tmp/artifacts
      - run:
          name: Move binaries to artifacts directory
          command: mv bin/* /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  cloud_query:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
